API:
    token: YOUR_API_ACCESS_TOKEN
export_options:
    export_path:
    filename:
    csv:
        export_inactive_items: false
preferences:
sync_delay_in_seconds: 36000
media_sync_offset_in_seconds: 600
